name: CI

on:
  push:
    branches-ignore: [
        # Renovate branches are always PRs, so they will be covered
        # by the pull_request event.
        "renovate/**",
        # Branches with the `gh-readonly-queue` prefix are used by the
        # merge queue, so they are already covered by the `merge_group` event.
        "gh-readonly-queue/**",
      ]
  pull_request:
  merge_group:

env:
  #
  # Keep in sync with cts.yml
  #

  #
  # Dependency versioning
  #

  # This is the MSRV used by all repository infrastructure.
  REPO_MSRV: "1.93"
  # This is the MSRV used by `wgpu` itself.
  WGPU_MSRV: "1.87"
  # This is the MSRV used by the `wgpu-core`, `wgpu-hal`, and `wgpu-types` crates,
  # to ensure that they can be used with firefox.
  CORE_MSRV: "1.87"

  #
  # Build and test configuration
  #

  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  RUST_LOG: debug,wasm_bindgen_wasm_interpreter=warn,wasm_bindgen_cli_support=warn,walrus=warn,naga=info
  RUST_BACKTRACE: full
  PKG_CONFIG_ALLOW_CROSS: 1 # allow android to work
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  WASM_BINDGEN_TEST_TIMEOUT: 300 # 5 minutes
  CACHE_SUFFIX: e # cache busting
  WGPU_CI: true

  #
  # Runtime configuration
  #

  LVP_POISON_MEMORY: true # to test memory init; see docs/testing.md
  WGPU_DX12_COMPILER: dxc

# Every time a PR is pushed to, cancel any previous jobs. This
# makes us behave nicer to github and get faster turnaround times
# on PRs that are pushed to multiple times in rapid succession.
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

# We distinguish the following kinds of builds:
# - native: build for the same target as we compile on
# - web: build for the Web
# - em: build for the Emscripten

# For build time and size optimization we disable debug symbols
# entirely on clippy jobs and reduce it to line-numbers
# only for ones where we run tests.
#
# Additionally, we disable incremental builds entirely
# as our caching system doesn't actually cache our crates.
# It adds overhead to the build and another point of failure.

jobs:
  gpu-test:
    # runtime is normally 5-15 minutes
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          # Mac
          - name: Mac aarch64
            os: macos-14

          # Linux
          - name: Linux x86_64
            os: ubuntu-24.04

    name: Test ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install repo MSRV toolchain
        run: |
          rustup toolchain install ${{ env.REPO_MSRV }} --no-self-update --profile=minimal -c llvm-tools
          cargo -V

      - name: Install `cargo-nextest` and `cargo-llvm-cov`
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov

      - name: Debug symbols to line-tables-only
        shell: bash
        run: |
          mkdir -p .cargo

          cat <<EOF >> .cargo/config.toml
            [profile.dev]
            debug = "line-tables-only"
          EOF

        # Cache step must go before warp and mesa install on windows as they write into the
        # target directory, and rust-cache will overwrite the entirety of the target directory.
      - name: Caching
        uses: Swatinem/rust-cache@v2
        with:
          key: test-${{ matrix.os }}-${{ env.CACHE_SUFFIX }}
          env-vars: ImageVersion
          save-if: ${{ github.ref == 'refs/heads/trunk' }}
          workspaces: |
            . -> target

      - name: (Windows) Install DXC
        if: matrix.os == 'windows-2022'
        uses: ./.github/actions/install-dxc

      - name: (Windows) Install WARP
        if: matrix.os == 'windows-2022'
        uses: ./.github/actions/install-warp
        with:
          target-dir: "target/llvm-cov-target/debug"

      - name: (Windows) Install Agility SDK
        if: matrix.os == 'windows-2022'
        uses: ./.github/actions/install-agility-sdk

      - name: (Windows) Install Mesa
        if: matrix.os == 'windows-2022'
        uses: ./.github/actions/install-mesa

      - name: (Windows) Install Vulkan SDK
        if: matrix.os == 'windows-2022'
        uses: ./.github/actions/install-vulkan-sdk

      - name: (Mac) Install Vulkan SDK
        if: matrix.os == 'macos-14'
        uses: ./.github/actions/install-vulkan-sdk

      - name: (Linux) Install Vulkan SDK
        if: matrix.os == 'ubuntu-24.04'
        uses: ./.github/actions/install-vulkan-sdk

      - name: (Linux) Install Mesa
        if: matrix.os == 'ubuntu-24.04'
        uses: ./.github/actions/install-mesa

      - name: Delete Naga snapshots
        shell: bash
        run: |
          set -e

          # Delete snapshots so we can ensure there aren't any excess output files.
          rm -r naga/tests/out

      - name: Run tests
        shell: bash
        run: |
          set -e

          cargo --locked xtask test --llvm-cov

      - name: Check Naga snapshots
        # git diff doesn't check untracked files, we need to stage those then compare with HEAD.
        run: git add . && git diff --exit-code HEAD naga/tests/out

      - uses: actions/upload-artifact@v7
        name: Upload comparison images
        if: always() # We want artifacts even if the tests fail.
        with:
          name: comparison-images-${{ matrix.os }}
          path: |
            **/*-actual.png
            **/*-difference.png

      # Print GPU configuration so we can see what features were available during the test.
      - name: Print GPU configurations
        if: always() # We want this information even if the tests fail.
        shell: bash
        run: |
          set -e

          cat .gpuconfig

      - name: Generate coverage report
        id: coverage
        shell: bash
        continue-on-error: true
        run: |
          set -e

          cargo --locked llvm-cov report --lcov --output-path lcov.info

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v7
        if: steps.coverage.outcome == 'success'
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

